-- Insert Main Topics
INSERT INTO "MainTopic" ("name") VALUES
  ('Life'),
  ('Self Improvement'),
  ('Health'),
  ('Work'),
  ('Artificial Intelligence'),
  ('Programming Languages'),
  ('Art'),
  ('DevOps'),
  ('Data Science'),
  ('Blockchain'),
  ('Development');

-- Insert Subtopics and relate them to Main Topics
INSERT INTO "Topic" ("name", "mainTopicId") VALUES
  ('Adoption', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Children', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Elder Care', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Fatherhood', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Motherhood', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Parenting', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Pregnancy', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  ('Seniors', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Life')),
  
  ('Anxiety', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Counseling', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Grief', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Life Lessons', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Self-awareness', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Stress', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Therapy', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),
  ('Trauma', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Self Improvement')),

  ('Aging', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Coronavirus', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Covid-19', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Death And Dying', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Disease', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Fitness', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Mens Health', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Nutrition', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Sleep', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Trans Healthcare', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Vaccines', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Weight Loss', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),
  ('Womens Health', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Health')),

  ('Entrepreneurship', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Work')),
  ('Freelancing', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Work')),
  ('Small Business', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Work')),
  ('Startups', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Work')),

  ('ChatGPT', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),
  ('Conversational AI', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),
  ('Deep Learning', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),
  ('Large Language Models', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),
  ('Machine Learning', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),
  ('NLP', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),
  ('Voice Assistant', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Artificial Intelligence')),

  ('Angular', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('CSS', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('HTML', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('Java', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('JavaScript', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('Nodejs', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('Python', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('React', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('NextJS', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('Ruby', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),
  ('Typescript', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Programming Languages')),

  ('Comics', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Contemporary Art', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Drawing', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Fine Art', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Generative Art', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Illustration', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Painting', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Portraits', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Street Art', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Animation', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('3d animation', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('Manga', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),
  ('2d animation', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Art')),

  ('AWS', (SELECT "id" FROM "MainTopic" WHERE "name" = 'DevOps')),
  ('Databricks', (SELECT "id" FROM "MainTopic" WHERE "name" = 'DevOps')),
  ('Docker', (SELECT "id" FROM "MainTopic" WHERE "name" = 'DevOps')),
  ('Kubernetes', (SELECT "id" FROM "MainTopic" WHERE "name" = 'DevOps')),
  ('Terraform', (SELECT "id" FROM "MainTopic" WHERE "name" = 'DevOps')),

  ('Analytics', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Data Science')),
  ('Data Engineering', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Data Science')),
  ('Data Visualization', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Data Science')),
  ('Database Design', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Data Science')),
  ('Sql', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Data Science')),

  ('Bitcoin', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Blockchain')),
  ('Cryptocurrency', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Blockchain')),
  ('Decentralized Finance', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Blockchain')),
  ('Ethereum', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Blockchain')),
  ('Nft', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Blockchain')),
  ('Web3', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Blockchain')),

  ('Android Development', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('Coding', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('Flutter', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('React Native', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('Frontend Engineering', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('iOS Development', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('Mobile Development', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('Software Engineering', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development')),
  ('Web Development', (SELECT "id" FROM "MainTopic" WHERE "name" = 'Development'));

